proposta/urls.py
# -*- Mode: Python; coding: utf-8 -*-
from django.conf.urls import *
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.conf import settings
from . import views
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import include
from django.urls import path, re_path #url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



urlpatterns = [
    path('proposta/<int:id>/', views.proposta, name='proposta'), 
    path('admin/', admin.site.urls),
    ]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = format_suffix_patterns(urlpatterns)

proposta/core/models.py
# -*- Mode: Python; coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib import admin
from django.utils.html import format_html
from django.db.models import Sum,Avg
from localflavor.br.br_states import STATE_CHOICES
from django.utils.safestring import mark_safe
from django.contrib.admin.views.main import ChangeList


class Cliente(models.Model):
	nome = models.CharField(u'Nome', max_length=100)

	def __str__(self):
		return self.nome

class Proposta(models.Model):
	cliente = models.ForeignKey("Cliente", on_delete=models.CASCADE)
	cpf = models.CharField(u'CPF', blank=True, max_length=14)
	cnpj = models.CharField(u'CNPJ', blank=True, max_length=18)
	endereco = models.CharField(u'Endereço', blank=True, max_length=200)
	bairro = models.CharField(u'Bairro', blank=True, max_length=100)
	cidade = models.CharField(u'Cidade', blank=True, max_length=100)
	estado = models.CharField(max_length=2, null=True, blank=True, choices=STATE_CHOICES)
	data = models.DateField(u'Data de Emissão' )
	VALIDADE_CHOICES = (
		('Quinze','15 (Quinze)'),
		('Trinta','30 (Trinta)'),
		('Sessenta','60 (Sessenta)'),
		)

	validade = models.CharField(u'Validade', blank=True, max_length=200, choices = VALIDADE_CHOICES) 
	valor = models.DecimalField(u'Valor a pagar', max_digits=8, decimal_places=2)
	CATEGORY_CHOICES = (
			('Atrasado','Atrasado'),
			('AVencer','Á Vencer'),
			('Pago','Pago'),
			)

	situacao = models.CharField(u'Situação', max_length=200, choices = CATEGORY_CHOICES)
	pago = models.BooleanField(default=False)


	def imprimir(self):
			return mark_safe("""<a href=\"/proposta/%s/\" target="_blank"><img src=\"/static/images/b_print.png\"></a>""" % self.id)


	class Meta:
		ordering = ['-data']
		verbose_name = u'UMA PROPOSTA'
		verbose_name_plural = u'PROPOSTAS'

	def __str__(self):
		if self.cliente.nome:
			return self.cliente.nome
		else:
			return self.custom_alias_name

proposta/core/views.py
from django.shortcuts import render

# Create your views here.

proposta/views.py
# -*- Mode: Python; coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from proposta.core.models import Cliente, Proposta


# Proposta
@login_required(redirect_field_name='redirect_to')
def proposta(request, id=None, *args, **kwargs):
	contexto = {}
	contexto['proposta_base'] = Proposta.objects.get(id=id)

	return render(request, "proposta.html", contexto)

web_project/core/views.py
from django.shortcuts import render

# Create your views here.

web_project/views.py
# -*- Mode: Python; coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from web_project.core.models import Cliente, Proposta


# Proposta
@login_required(redirect_field_name='redirect_to')
def proposta(request, id=None, *args, **kwargs):
	contexto = {}
	contexto['proposta_base'] = Proposta.objects.get(id=id)

	return render(request, "proposta.html", contexto)

templates/proposta.html
{% load static %}<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <title>PROPOSTA - {{ proposta_base.cliente.nome }} - {{ proposta_base.data|date:"d F Y" }}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  
  <link rel="stylesheet" href="{% static 'css/style-proposta.css' %}">
</head>
<body>
<div id="geral">
    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-md-2 col-sm-12">
                <div class="img-logo">
                    <img src="{% static 'images/logo.png' %}" alt="">
                </div>
            </div>
            <div class="col-lg-10 col-md-10 col-sm-12">
        <div class="topo center">
            <h3><strong>CONTRATO DE PRESTAÇÃO DE SERVIÇO DE ASSESSORIA JURIDICA MURILO HEYDE</strong></h3>
            <h4>MURILO HEYDE ASSESSORIA JURÍDICA - OAB/RS 97.756 OA/PT 33.356L</h4>
            <p>Rua:  - Bairro:  - Fone: <br>
            Site: www.muriloheydeassessoria.com.br / Email: contato@muriloheydeadv.com.br  
            <br>Cidade - Estado</p>

      </div>
      </div>
      </div>
          <div class="row">
            <hr>
            <div class="informacao-cliente">
              <div class="col-lg-6 col-md-6 col-sm-6">
                  <p> <strong>EMPRESA OU CLIENTE:</strong> {{ proposta_base.cliente.nome|upper }}</p>
                  {% if proposta_base.cpf %}
                  <p> <strong>CPF:</strong> {{ proposta_base.cpf }}</p>
                  {% else %}
                  <p> <strong>CNPJ:</strong> {{ proposta_base.cnpj }}</p>
                  {% endif %}
                  <p> <strong>ENDEREÇO:</strong> {{ proposta_base.endereco|upper }}</p>
              </div>
              <div class="col-lg-6 col-md-6 col-sm-6">
                  <p> <strong>BAIRRO:</strong> {{ proposta_base.bairro|upper }}</p>
                  <p> <strong>CIDADE:</strong> {{ proposta_base.cidade|upper }}</p>
                  <p> <strong>ESTADO:</strong> {{ proposta_base.get_estado_display|upper  }}</p>
              </div>
            </div>
          </div>
    </div>

    <div class="container">
      <div class="row"><br>
<hr>
<strong>I – DO OBJETO DO CONTRATO</strong><br>
 
O presente instrumento tem como OBJETO a prestação de serviços advocatícios<br>
<hr>
<strong>II - DAS ATIVIDADES</strong><br>

 
As atividades inclusas na prestação de serviço objeto deste instrumento são todas aquelas inerentes à profissão, quais sejam:<br>
  <p class="espaco">
- Praticar quaisquer atos e medidas necessárias e inerentes à causa, em todas as repartições públicas da União, dos Estados ou dos Municípios, bem como órgãos a estes ligados direta ou indiretamente, seja por delegação, concessão ou outros meios, bem como de estabelecimentos particulares;;<br>
- Praticar todos os atos inerentes ao exercício da advocacia e aqueles constantes no Estatuto da Ordem dos Advogados do Brasil, bem como os especificados no Instrumento Procuratório;<br>
</p>
  <hr>
 <strong>III - DAS DESPESAS</strong><br>

 
 Todas as despesas efetuadas pelo CONTRATADO, ligadas direta ou indiretamente com o processo, incluindo-se fotocópias, emolumentos, viagens, custas, entre outros, ficarão a cargo da CONTRATANTE.<br>
Todas as despesas serão acompanhadas de recibo, devidamente preparado e assinado pelo CONTRATADO.<br>
 <p class="espaco">
  <hr>
<strong>IV - DA COBRANÇA</strong><br>


As partes acordam que facultará ao CONTRATADO, o direito de realizar a cobrança dos honorários por todos os meios admitidos em direito.<br>
 <hr>
 <strong>V - DOS HONORÁRIOS</strong><br>

Pelos serviços prestados, o CONTRATADO receberá a título de honorários contratados o percentual fixo de 30% sobre o proveito econômico obtido ao final da demananda, mais o valor de:<br>
- Valor: <b>R$ {{proposta_base.valor}}</b> <br>  

- O CONTRATANTE efetuará o pagamento do serviço da seguinte forma:<br>
<p class="espaco">
{% for item_da_proposta in proposta_base.pagamento_set.all %}

- <b>R$</b> {{item_da_proposta.valor}} <b>( {{item_da_proposta.valor_extenso|capfirst|upper}} )</b>, {{item_da_proposta.descricao|capfirst}}.<br>
 {% endfor %}
</p>
<hr>
<strong>VI - DA RESCISÃO DO CONTRATUAL</strong><br>

Agindo a CONTRATANTE de forma dolosa ou culposa em face do CONTRATADO, restará facultado a estes, rescindir o contrato, substabelecendo sem reserva de iguais e se exonerando de todas obrigações.<br>
 <hr>
<strong>VII - PRAZO DE VIGÊNCIA DO PRESENTE CONTRATO</strong><br>

Com exceção dos serviços de implantação do sistema o presente contrato vigorará por prazo determinado de 1 (um) ano, podendo ser renovado posteriormente.
 
E, por assim estarem justos e contratados, firmam o presente contrato em duas vias de igual teor e forma.<br>
<hr>


<hr>
<strong><i>FORO: Para dirimir quaisquer controvérsias oriundas do CONTRATO, as partes elegem o foro da comarca de Osório/RS;<br>
  Por estarem assim justos e contratados, firmam o presente instrumento, em duas vias de igual teor.</i></strong> 
<br>
<hr>
<div class="validade"><i></i>Proposta válida por {{ proposta_base.get_validade_display }} dias</div><br> 

<div class="infor-data">OSÓRIO - RS - {{ proposta_base.data|date|upper }}</div></b><br>

<div class="separador text-center">
_________________________________________ <br> 
MURILO HEYDE <br> 
<p>OAB/RS 97.756 OA/PT 33.356L</p>


_________________________________________<br> 
{{proposta_base.cliente.nome}}<br> 
{% if proposta_base.cpf %}
  <p>CPF: {{ proposta_base.cpf }}</p>
{% else %}
  <p>CNPJ: {{ proposta_base.cnpj }}</p>
{% endif %}

      </div>
</div>
    </div>
</div>
</body>
</html>